import mongoose from "mongoose";
import type { INote } from "../types/entities.js";

const NoteSchema = new mongoose.Schema<INote>(
  {
    title: { type: String, required: true },  

    sources: [{ type: mongoose.Schema.Types.ObjectId, ref: "Source" }],
    content: { type: String },
    summary: { type: String },
    quizzes: [{ type: mongoose.Schema.Types.ObjectId, ref: "Quiz" }], // Optional, generated by AI

    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  },
  { timestamps: true }
);

export default mongoose.model("Note", NoteSchema);
